### ISSUE TITLE
Interval counter kicks-in after a poll ends, creating gaps in polls

### ISSUE THREAD

**Issue by luminous706** [logstash-plugins/logstash-input-snmp#94] opened 2021-03-20 21:50 UTC
I'm trying to poll a Cisco Nexus switch with hundreds of interfaces. 

Interval is set at 60 seconds, I need to poll/walk that device every minute. Problem is, there are gaps and sometimes it misses a minute because the intervals start after a poll finishes. For example:

First SNMP walk starts at 17:00:00s, takes 35 seconds to finish, interval will start counting 60 seconds from 17:00:35s, 
Second SNMP walk starts at 17:01:35s, takes 35 seconds to finish, interval will start counting from 17:02:10s.

Notice above that there were 2 polls, and the data arrived into Elasticsearch at precisely 17:00:35s, and 17:02:10s. No data arrived at 17:01.

The "interval" option should not start counting when a pool finishes, it should just run at regular, predictable intervals. At the moment, if I set my interval every 60 seconds, it's actually not true, it's 60 seconds + the amount of time SNMP does a walk.

My graphs are full of gaps because of this.

**Comment by gauravubnare** [comment] 2021-04-19 13:29
Hello,

we are also facing the same issue... can anyone pls assist on this. 

Thanks

**Comment by gauravubnare** [comment] 2021-08-31 10:00
Hi,

can anyone please help us with this. we have around 100+ routers and we are facing lots of issues with the SNMP plugin like the data plotted on the dashboard has lots of gaps and dips in the inbound/outbound utilization graph we have. polling interval is 5 mins... 

to solve this problem. we had one pipeline with 100 hosts earlier we split the pipeline to 1 pipeline with - 5 hosts that actually solved lots of issues... but still, it is not fully stable.. and also ending up using a lot of resources on the logstash server because of the multiple pipelines...

@kaisecheng @colinsurprenant pls help us resolve this.

Thanks

![snmp gap](https://user-images.githubusercontent.com/36446654/131483160-aa0ea0a6-dfcb-411a-a936-822a64237e9c.png)

![snmp dip](https://user-images.githubusercontent.com/36446654/131483197-05ba2acd-2902-4da4-ba93-177077e7686f.png)

**Comment by kaisecheng** [comment] 2021-08-31 10:43
Regarding the `interval` behaviour, the polling is not triggered by a scheduler but a loop with [sleep](https://github.com/logstash-plugins/logstash-input-snmp/blob/master/lib/logstash/inputs/snmp.rb#L211). There is a [PR](https://github.com/logstash-plugins/logstash-input-snmp/pull/95) clarify the wording of the doc. I think the better way out is to use [scheduler](https://github.com/jmettraux/rufus-scheduler) with `overlap` option to `false`. The team does not have the capacity to make the change. We are more than happy to review PR from the community to enhance this feature.

**Comment by kaisecheng** [comment] 2021-08-31 15:43
@gauravubnare
For us to investigate whether there is a more in-depth issue, I would suggest you provide further information about the environment:
 1. How is logstash configured, can you provide a sample pipeline config?
 2. Can you provide any logs during the timeframe where you are seeing the issue?
 3. Have you confirmed that there are no network issues at the time?

If you feel this is something that you need, I would suggest you file a different issue provided that this could be a different topic that falls outside of this issue.

**Comment by axrayn** [comment] 2021-09-01 12:49
Duplicate of https://github.com/logstash-plugins/logstash-input-snmp/issues/61

**Comment by gauravubnare** [comment] 2021-09-07 13:10
Hi @axrayn,  I am facing the same issue. but is it resolved in that issue? 
please help me resolve it.

**Comment by yaauie** [comment] 2021-09-21 19:58
Resolved with #100 and released in v1.2.8 of this plugin.

You can upgrade this plugin in [the usual way](https://www.elastic.co/guide/en/logstash/current/working-with-plugins.html#updating-plugins):

> ~~~ sh
> bin/logstash-plugin update logstash-input-snmp
> ~~~

**Closed by yaauie** 2021-09-21 19:58 UTC
Labels: status:needs-info
